package mx.uam.sapcyti.audit.domain.model;

/**
 * Well-known audit actions emitted by other Bounded Contexts.
 */
public enum KnownAuditActions {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_CHANGED,
    RBAC_VIOLATION_DETECTED,
    USER_CREATED,
    STUDENT_REGISTERED,
    STUDENT_UPDATED,
    STUDENT_PROGRAM_UPDATED,
    PROFESSOR_REGISTERED,
    PROFESSOR_UPDATED,
    PROFESSOR_DEACTIVATED,
    PROFESSOR_RESTORED,
    ACADEMIC_OFFER_UPLOADED,
    UEA_REGISTERED,
    UEA_BULK_UPLOADED,
    UEA_UPDATED,
    UEA_DEACTIVATED,
    UEA_RESTORED,
    ANNUAL_PLAN_CREATED,
    ANNUAL_PLAN_ENTRIES_SAVED,
    ANNUAL_PLAN_STATUS_CHANGED,
    ANNUAL_PLAN_EXPORTED,
    ENROLLMENT_PERIOD_OPENED,
    COURSES_SELECTED,
    ENROLLMENT_APPROVED_BY_ADVISOR,
    ENROLLMENT_REJECTED_BY_ADVISOR,
    ENROLLMENT_FINALIZED
}
